FROM alpine:latest
RUN echo "please run 'CGO_ENABLED=0 GOOS=linux go build -o ./bin/maple-server -a -ldflags '-extldflags \"-static\"' .' first"
# Copy our static executable.
COPY ./bin/maple-server /go/bin/maple-server
# Run the hello binary.
ENTRYPOINT ["/go/bin/maple-server"]